sh 'pip install robotframework'
sh 'pip install robotframework-seleniumlibrary'
sh 'pip install robotframework-appiumlibrary'
sh 'pip install robotframework-requests'
sh 'pip install robotframework-databaselibrary'
sh 'pip install robotframework-SikuliLibrary'
